const quotes = {
  neutralQuotes: [
    'I am doing the best I can, and that is enough.',
    'I trust myself to make the right decisions.',
    'I am grounded, mindful, and at peace.',
    'Each day is a fresh start.',
    'I have everything I need within me.',
    'I am present in this moment, exactly as I am.',
    'I release what I cannot control and focus on what I can.',
    'I am steady, calm, and capable.',
    'Progress, not perfection, is my goal.',
    'I choose how I respond to everything around me.',
  ],
  sadQuotes: [
    "It's okay to feel this way. Emotions come and go like waves.",
    'I am allowed to rest. Healing takes time.',
    'Even on my hard days, I am worthy of love and compassion.',
    'This moment is tough, but it won't last forever.',
    'I've made it through every difficult day so far. I can do this too.',
    'Sadness is not weakness — it is proof that I feel deeply.',
    'I give myself permission to grieve and to grow.',
    'I am gentle with myself during difficult times.',
    'My pain is valid, and so is my ability to heal from it.',
    'Tears are not failure. They are part of being human.',
  ],
  angryQuotes: [
    'I can feel anger without letting it control me.',
    'It's okay to be mad — my emotions are valid.',
    'I choose to respond, not react.',
    'I am allowed to take space to cool down and reflect.',
    'My anger is a signal, not a sentence. I will listen and then release.',
    'I breathe through my frustration and reclaim my calm.',
    'I acknowledge my anger and choose peace anyway.',
    'I release resentment and make room for clarity.',
    'My boundaries are worth protecting, and I can voice them with calm.',
    'I do not need to burn bridges to stand my ground.',
  ],
  happyQuotes: [
    'I accept joy as my standard of living.',
    'Kawhi Leonard plays basketball today.',
    'I take ownership of my happiness.',
    'I prioritize things that bring me joy.',
    'I choose to celebrate the good things in my life.',
    'Gratitude opens the door to more abundance.',
    'I radiate warmth, and it comes back to me.',
    'My happiness is not dependent on circumstances — it comes from within.',
    'I give myself fully to moments of joy without guilt.',
    'The good in my life is real, and I deserve to enjoy it.',
  ],
  fearQuotes: [
    'The best way out is always through.',
    'Everything you want is on the other side of fear.',
    'The scariest moment is always just before you start.',
    'You gain strength, courage, and confidence by every experience in which you really stop to look fear in the face.',
    'Never let the fear of striking out get in your way.',
    'Courage is not the absence of fear — it is acting despite it.',
    'I have faced uncertainty before and found my way through.',
    'Fear is a visitor, not a permanent resident.',
    'I am braver than I believe and stronger than I feel.',
    'The unknown holds possibility just as much as it holds risk.',
  ],
}

export default quotes;